### ISSUE TITLE
(2) Datenbank-Methoden auslagern

### ISSUE THREAD

**Issue by FlyingWalross** [Oscavian/ss22-itp-g02#25]
- [x] createGroup
- [x] getUserGroups
- [x] userIsInGroup
- [x] getGroupName
- [x] getGroupChatId
- [x] checkUserNameAvailable
- [x] getUserData
- [x] registerUser

**Comment by Oscavian** [comment]
siehe 8edeb142a31ca6cc8b730cae046fbd5475c67041
@FlyingWalross @duellieren 

- bisherige Group-Requests sind jetzt an da neue Klassenmodell angepasst
 - die alten Datenbankmethoden habe ich dementsprechend gelöscht
 - offen wären jetzt noch die bestehenden User-Methoden

Bitte sagt sofort Bescheid, sollte etwas für euch unklar sein!
