### ISSUE TITLE
(3) Classify Backend

### ISSUE THREAD

**Issue by FlyingWalross** [Oscavian/ss22-itp-g02#28]
- Assignments als Beispiel hernehmen

**Comment by Oscavian** [comment]
siehe 52acb486d3424f5de70d2decb08d56840187b107
- Methoden aus MainLogic provisorisch in die jeweiligen Handler-Klassen verschoben
- Basis der Handler-Klassen implementiert -> können jetzt Stück für Stück erweitert werden
